apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client-secret
  namespace: grafana
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: oauth-client-secret
  data:
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: nerc/nerc-ocp-infra/dex/dex-clients
      property: GRAFANA_SECRET

  - secretKey: GF_AUTH_GENERIC_TLSCACERT
    remoteRef:
      key: nerc/nerc-ocp-infra/dex/grafanas
      property: GF_TLSCACERT

  - secretKey: GF_AUTH_GENERIC_TLSCLIENTCERT
    remoteRef:
      key: nerc/nerc-ocp-infra/dex/grafanas
      property: GF_TLSCLIENTCERT

  - secretKey: GF_AUTH_GENERIC_TLSCLIENTKEY
    remoteRef:
      key: nerc/nerc-ocp-infra/dex/grafanas
      property: GF_TLSCLIENTKEY
