apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-thanos-object-storage
  namespace: openshift-logging
spec:
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/loki-thanos-object-storage
