apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nerc-secret-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes/nerc-ocp-obs
