apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: logs-bucket-class
  namespace: openshift-storage
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - logs-backing-store
