apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: logsarchive-bucket-class
  namespace: openshift-storage
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - logsarchive-backing-store
